from processor import convert_to_wav, process_audio, compute_dist

convert_to_wav('english_example.mp3')
# convert_to_wav('bad_example.mp3')
#
y, sr = process_audio('Test.wav')
print('Test')
compute_dist(y,sr)
y, sr = process_audio('model.wav')
print('control')
compute_dist(y,sr)
y, sr = process_audio('russian_example.wav')
print('Russian')
compute_dist(y,sr)
y, sr = process_audio('english_example.wav')
print('English')
compute_dist(y,sr)
y, sr = process_audio('good_example.wav')
print('Good')
compute_dist(y,sr)
y, sr = process_audio('bad_example.wav')
print('Bad')
compute_dist(y,sr)
